[package]
version = "0.1.0"
name = "fibonacci-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", rev="2c1a183b8620a5a5e6891010dd0e64879ad2ee3a" }
fibonacci-lib = { path = "../lib" }